next-version: 1.0
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
assembly-informational-format: '{InformationalVersion}'
mode: ContinuousDelivery
increment: Inherit
continuous-delivery-fallback-tag: ci
tag-prefix: '[vV]'
major-version-bump-message: '(breaking|major)'
minor-version-bump-message: '(feature|minor)'
patch-version-bump-message: '(fix|hotfix|bugfix)'
no-bump-message: '(none|skip|chore)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
tag-pre-release-weight: 60000
commit-message-incrementing: Enabled
ignore:
  sha: []
merge-message-formats: {}
update-build-number: true
