name: Commit Message Check

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - galaxy
      
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get PR Commits
      run: |
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo $PR_NUMBER
        git fetch origin pull/$PR_NUMBER/head:testpr
        git log master..testpr
        
