name: Commit Message Check

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - galaxy
      
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
