name: gitversion

on:
  push:
    branches: [ none ]

jobs:
  getversion:
    
    name: Determine Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: VersionConfig.yml

      - name: Display Version
        run: |
          echo "SemanticVersion: $GITVERSION_SEMVER"

      - name: Get version path
        id: branch
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ env.GITVERSION_SEMVER }}
          regex: "\\-[^\\-]*$"
          flags: "" # Optional, defaults to "g"
          replacement: ""

      - name: show version path
        run: echo "v${{ steps.branch.outputs.value }}"

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with: 
          tag: 'v${{ steps.branch.outputs.value }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate new tag
        id: gen_tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'v${{ steps.branch.outputs.value }}'
