name: gitversion

on:
  push:
    branches: [ main ]


jobs:
  getversion:
    
    name: Determine Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
#         with:
#           useConfigFile: true
#           configFilePath: VersionConfig.yml
